### ISSUE TITLE
Downloading minecraft

### ISSUE THREAD

**Issue by Roxve** [STierProgrammer/SinLauncher#6]
downloading Minecraft from manifest Json; we are using the offical Mojang meta format
## Todo
- [x] Downloading client.json and creating instance folder
- [x] parsing client.json
- [x] downloading client from client.json
